trigger:
  branches:
    include:
      - main  # Define the branch that triggers the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent

steps:
- checkout: self  # Ensure the repository is checked out

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'  # Use Python 3.x
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
    pip install ciscoisesdk
    pip install ciscoisesdk --upgrade
  displayName: 'Install Dependencies'

- script: |
    ls -al       # Debugging: list all files to ensure cisco_ise_1.py exists
    pwd          # Debugging: print the current working directory
    python hello_world.py
    python3 cisco_ise_1.py
  displayName: 'Pipeline Test 1'
